name: CI

on:
  push:
    branches: [main, v2]
  pull_request:

jobs:
  verify_files:
    name: Verify Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - name: Install Packages
        run: npm ci
      - name: Verify Release Routing
        run: node .github/release-routing/validate.mjs check-workflows
      - name: Lint Files
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - name: Install Packages
        run: npm ci
      - name: Unit Tests
        run: npm run test
      - name: Package Contract
        run: npm run test:package-contract
    # - name: ESBuild compatability
    # run: npm run test:esbuild
