name: CI

on:
  push:
    branches: [main, v2]
  pull_request:

jobs:
  verify_files:
    name: Verify Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install Packages
        run: pnpm install --frozen-lockfile
      - name: Lint Files
        run: pnpm run lint
      - name: Typecheck
        run: pnpm run typecheck

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install Packages
        run: pnpm install --frozen-lockfile
      - name: Unit Tests
        run: pnpm run test
      # - name: ESBuild compatability
      #   run: pnpm run test:esbuild
